plugin: amazon.aws.aws_ec2
regions:
  - us-west-2
filters:
  tag:Name: demo-instance
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    prefix: tag_Name
compose:
  ansible_host: public_ip_address
  ansible_python_interpreter: /usr/bin/python3